language: python
python:
    - "3.6"

sudo: required

services:
  - docker

install:
  - docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD docker.saritasa.com
  - pip install -r requirements-travis.txt
  - fab project.init
  - fab project.build

before_script:
  - fab django.migrate

script:
  - fab django.run
