language: python
python:
    - "3.6"

sudo: required

services:
  - docker

before_install:
  # Let's stop postgresql
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

install:
  - docker login docker.saritasa.com --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
  - pip install -r .travis-requirements.txt

  # Compile pip dependencies
  - pip-compile --output-file requirements/development.txt requirements/development.in
  - pip-compile --output-file requirements/production.txt requirements/production.in
  - pip install --upgrade setuptools pip

  - cp config/settings/local.py.template config/settings/local.py

  - docker-compose build web postgres redis
  #- docker-compose up web postgres redis

  - docker-compose run --rm web python3 manage.py makemigrations
  - docker-compose run --rm web python3 manage.py migrate

  - docker-compose run --rm web python3 manage.py test -v 2 --noinput


#before_script:
#  - fab django.migrate

script:
  - docker-compose run --rm web python3 manage.py runserver_plus 0.0.0.0:8000  --reloader-type stat --pm
