language: python
python:
    - "3.6"

sudo: required

services:
  - docker

before_install:
  # Let's stop postgresql
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

install:
  - docker login docker.saritasa.com --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
  - pip install -r .travis-requirements.txt
  - fab project.init < .travis-superuser.txt
  - MUSIC_STORE_EXERCISE_ENVIRONMENT=local

before_script:
  - fab django.migrate

script:
  - fab django.run
