language: python

sudo: required

services:
  - docker

install:
  - pip install fabric
  - pip install configparser
  - fab project.build

before_script:
  - fab django.migrate

script:
  - fab django.run
