language: python
python:
    - "3.6"

sudo: required

notifications:
  email: false

services:
  - docker

branches:
  only:
    - develop
    - feature/travis-ci-start

before_install:
  # Let's stop postgresql
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

install:
  - docker login docker.saritasa.com --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
  - pip install -r .travis-requirements.txt

  # Compile pip dependencies
  - pip-compile --output-file requirements/development.txt requirements/development.in
  - pip-compile --output-file requirements/production.txt requirements/production.in
  - pip install --upgrade setuptools pip

  - cp config/settings/local.py.template config/settings/local.py

  - docker-compose build web postgres redis


before_script:
  - docker-compose run --rm web python3 manage.py makemigrations
  - docker-compose run --rm web python3 manage.py migrate
  - cp requirements/development.txt requirements.txt

  #- docker-compose run --rm web python3 manage.py runserver_plus 0.0.0.0:8000  --reloader-type stat --pm

script:
  - docker-compose run --rm web python3 manage.py test -v 2 --noinput --parallel

after_script:
  - docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
  # - docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .
  - docker tag web registry.heroku.com/$HEROKU_APP_NAME/web
  - docker push registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: heroku
  buildpack: python
  app: musicstore
  api_key: 11fd19bd-ec5c-4a59-afee-bda09387194c
  skip_cleanup: true
  on:
    all_branches: true
    python: "3.6"
  run:
    - "pip install -r requirements.txt"
    - "python3 manage.py migrate --all"
    #- "python3 manage.py syncdb --noinput"
    #- python3 manage.py runserver_plus 0.0.0.0:8000  --reloader-type stat --pm
