language: python
python:
    - "3.6"

sudo: required

services:
  - docker

install:
  - pip install fabric3
  - pip install configparser
  - pip install pip-compile
  - fab project.init
  - fab project.build

before_script:
  - fab django.migrate

script:
  - fab django.run
