language: python
python:
  - "3.6"

sudo: required

notifications:
  email: false

services:
  - docker

branches:
  only:
    - develop
    - feature/travis-ci-start

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - pip install -r .travis-requirements.txt

install:
  # Compile pip dependencies
  - pip-compile --output-file requirements/development.txt requirements/development.in
  - pip-compile --output-file requirements/production.txt requirements/production.in
  - pip install --upgrade setuptools pip
  - cp config/settings/local.py.template config/settings/local.py

before_script:
  - docker login docker.saritasa.com --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
  - docker-compose build web
  - docker-compose run --rm web python3 manage.py makemigrations
  - docker-compose run --rm web python3 manage.py migrate

script:
  - docker-compose run --rm web python3 manage.py test -v 2 --noinput --parallel

after_success:
  # send container to heroku
  - /usr/local/heroku/bin/heroku heroku container:push musicstoreexercise_web -a musicstore
